In [3]:
import pandas as pd

In [4]:
retail = pd.read_csv(r"C:\Users\Kevin\Desktop\retail.csv", parse_dates=["date"])
retail.head()

        id       date  store_nbr      family  sales  onpromotion
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945 2016-01-01          1   BABY CARE    0.0            0
2  1945946 2016-01-01          1      BEAUTY    0.0            0
3  1945947 2016-01-01          1   BEVERAGES    0.0            0
4  1945948 2016-01-01          1       BOOKS    0.0            0

In [5]:
retail.index = retail["date"]
retail.head()

                 id       date  store_nbr      family  sales  onpromotion
date
2016-01-01  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0
2016-01-01  1945945 2016-01-01          1   BABY CARE    0.0            0
2016-01-01  1945946 2016-01-01          1      BEAUTY    0.0            0
2016-01-01  1945947 2016-01-01          1   BEVERAGES    0.0            0
2016-01-01  1945948 2016-01-01          1       BOOKS    0.0            0

In [7]:
retail.loc["2016":"2017-08"]

,id,date,store_nbr,family,sales,onpromotion
date,,,,,,
2016-01-01,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
2016-01-01,1945945,2016-01-01,1,BABY CARE,0.000,0
2016-01-01,1945946,2016-01-01,1,BEAUTY,0.000,0
2016-01-01,1945947,2016-01-01,1,BEVERAGES,0.000,0
2016-01-01,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
2017-08-15,3000883,2017-08-15,9,POULTRY,438.133,0
2017-08-15,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
2017-08-15,3000885,2017-08-15,9,PRODUCE,2419.729,148
2017-08-15,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
2017-08-15,3000887,2017-08-15,9,SEAFOOD,16.000,0